package org.wilsonks.may30.java_object_equality.custom_classes;

public class JavaRecordModernWay {
    public static void main(String[] args) {
        EmployeeRecord er1 = new EmployeeRecord("John", "Doe");
        EmployeeRecord er2 = new EmployeeRecord("John", "Doe");

        System.out.println(er1 == er2); // false because er1 and er2 are different objects in memory
        System.out.println(er1.equals(er2)); // true because the equals method generated by the record compares

    }
}

record EmployeeRecord(String firstName, String lastName) {
    public String getFullName() {
        return firstName + " " + lastName;
    }
}