
/*
 *
 *  * =============================================================================
 *  * Project    : Java21MasterList
 *  * File       : RecordEquals.java
 *  * Created On : 2026-06-03 09:36
 *  * Author     : Wilson K Sam
 *  * Copyright  : (c) 2026 Wilson K Sam
 *  * =============================================================================
 *  *
 *  * Description:
 *  * This source file is part of a coding practice project created for learning,
 *  * experimentation, interview preparation, and demonstration of software
 *  * development concepts and best practices.
 *  *
 *  * Notes:
 *  * -
 *  *
 *  * =============================================================================
 *
 */

package org.wilsonks.java17.java_records;

public class AutoGenEquals {

    public static final String DESCRIPTION = """
        This class demonstrates the behavior of the equals method in Java records.
        In Java, records automatically generate an equals method that compares the state of the record's components.
        This means that two record instances with the same component values will be considered equal, even if they are different objects in memory.
        This is a key feature of records that distinguishes them from regular classes, where the default equals method compares object references.
        By using records, developers can easily create immutable data carriers with value-based equality semantics, which can lead to cleaner and more maintainable code.
    """;

    record Person(String name, int age) {
        // The equals method is automatically generated by the record, so we don't need to implement it ourselves.
    }

    public static void main(String[] args) {
        System.out.println(DESCRIPTION);
    }


}

