/*
 *
 *  * =============================================================================
 *  * Project    : Java21MasterList
 *  * File       : JavaRecordModernWay.java
 *  * Created On : 2026-06-04 09:00
 *  * Author     : Wilson K Sam
 *  * Copyright  : (c) 2026 Wilson K Sam
 *  * =============================================================================
 *  *
 *  * Description:
 *  * This source file is part of a coding practice project created for learning,
 *  * experimentation, interview preparation, and demonstration of software
 *  * development concepts and best practices.
 *  *
 *   * Purpose:
 *   * -
 *  * Notes:
 *  * -
 *  *
 *  * =============================================================================
 *
 */

package org.wilsonks.core_java.java_object_equality.custom_classes;

public class JavaRecordModernWay {
    public static void main(String[] args) {
        EmployeeRecord er1 = new EmployeeRecord("John", "Doe");
        EmployeeRecord er2 = new EmployeeRecord("John", "Doe");

        System.out.println(er1 == er2); // false because er1 and er2 are different objects in memory
        System.out.println(er1.equals(er2)); // true because the equals method generated by the record compares

    }
}

record EmployeeRecord(String firstName, String lastName) {
    public String getFullName() {
        return firstName + " " + lastName;
    }
}